openapi: "3.0.0"
info:
  version: 1.0.0
  title: Test API
paths:
  /orders:
    post:
      operationId: createOrder
      # OpenAPI specification extensions
      # `x-yc-apigateway-integration` is used to specify the function to be called
      # Additional info: https://cloud.yandex.ru/docs/api-gateway/concepts/extensions/cloud-functions
      x-yc-apigateway-integration:
        type: cloud_functions
        function_id: ${orders_function}
        service_account_id: ${sa_id}
        payload_format_version: "1.0"

      # Request body schema
      # Docs: https://spec.openapis.org/oas/latest.html#request-body-object
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [ "orderId", "customerId", "orderItems" ]
              properties:
                orderId:
                  type: string
                customerId:
                  type: string
                orderItems:
                  type: array
                  items:
                    type: object
                    properties:
                      name:
                        type: string
                      quantity:
                        type: integer
                      price:
                        type: number
              additionalProperties: false
      # Response body schema
      # Docs: https://spec.openapis.org/oas/latest.html#responses-object
      responses:
        '200':
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                  orderId:
                    type: string
          description: Success
    get:
      operationId: listOrders
      x-yc-apigateway-integration:
        type: cloud_functions
        function_id: ${orders_function}
        service_account_id: ${sa_id}
        payload_format_version: "1.0"
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    orderId:
                      type: string
                    customerId:
                      type: string
                    orderItems:
                      type: array
                      items:
                        type: object
                        properties:
                          name:
                            type: string
                          quantity:
                            type: integer
                          price:
                            type: number
                  additionalProperties: false
          description: Success
  /orders/{orderId}:
    get:
      operationId: getOrder
      x-yc-apigateway-integration:
        type: cloud_functions
        function_id: ${orders_function}
        service_account_id: ${sa_id}
        payload_format_version: "1.0"
      parameters:
        - name: orderId
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                type: object
                properties:
                  orderId:
                    type: string
                  customerId:
                    type: string
                  orderItems:
                    type: array
                    items:
                      type: object
                      properties:
                        name:
                          type: string
                        quantity:
                          type: integer
                        price:
                          type: number
                additionalProperties: false
          description: Success
